# Generated by Django 4.1.7 on 2023-03-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcome',
            name='file',
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='English', max_length=20),
        ),
    ]
