# Generated by Django 4.1.7 on 2023-03-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mainmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('register', models.CharField(max_length=50)),
                ('more_info', models.CharField(max_length=50)),
                ('main_menu', models.CharField(max_length=50)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bot')),
            ],
            options={
                'verbose_name_plural': 'PresentationMenu',
            },
        ),
    ]
