# Generated by Django 4.1.7 on 2023-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_presentationmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('back', models.CharField(max_length=50)),
                ('main_menu', models.CharField(max_length=50)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bot')),
            ],
            options={
                'verbose_name_plural': 'VideoMenu',
            },
        ),
        migrations.CreateModel(
            name='VideoMenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('videoMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoMenu', to='core.videomenu')),
            ],
            options={
                'verbose_name_plural': 'VideoMenuOption',
            },
        ),
    ]
