# Generated by Django 4.1.7 on 2023-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_videomenu_videomenuoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomenuoption',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
