# Generated by Django 4.1.7 on 2023-03-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='registration_link',
        ),
        migrations.AddField(
            model_name='botuser',
            name='lead',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='BotUser', to='core.lead'),
            preserve_default=False,
        ),
    ]
