# Generated by Django 4.1.7 on 2023-03-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_botuser_registration_link_botuser_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('main_menu', models.CharField(max_length=50)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bot')),
            ],
            options={
                'verbose_name_plural': 'RegisterMenu',
            },
        ),
    ]
