# Generated by Django 4.1.7 on 2023-03-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registermenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BotUser', to='core.lead'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registermenu',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registermenu',
            name='main_menu',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
